import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import AppProvider from "@/components/Providers/AppProvider";
import { ViewTransitions } from "next-view-transitions";

const manrope = Manrope({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${manrope.className} antialiased`}>
          <AppProvider>{children}</AppProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
